### ISSUE TITLE
Logging in with Google: "This browser or app may not be secure"

### ISSUE THREAD

**Issue by margotr** [Atwix/phpstorm-plugin-feedback#93]
Hi,

I login to ChatGPT using Google, however that does not work here due to 'this browser or app may not be secure'. Has anyone found a workaround for this?

![image](https://github.com/user-attachments/assets/61ee9799-3adf-47ba-b742-9cb171ee51cf)

Thanks,
Margot

**Comment by bohdan-harniuk** [comment]
Hi @margotr ,

This feature has been discontinued and fully removed in the latest version of our plugin (2024.2.0). We made this decision because a superior alternative has been developed by the dedicated team at JetBrains. You can check it out here: https://www.jetbrains.com/ai/. Our focus remains on enhancing the development experience for Adobe Commerce/Magento, leaving AI-related functionalities to the official JetBrains channel.

Best regards,
